update step4
BogdanPerekhrest34/bookstore pull request #10
Opened 2022-03-22 11:15 UTC by BogdanPerekhrest34

checkout controller
cart controller
order_item controller
user/settigns -> privacy and addresses controller
omniauth controller

2022-03-22 14:16 UTC, nico-saj requested changes
Add specs

2022-03-22 14:16 UTC, nico-saj commented on app/services/users/settings/address_updater.rb
> +          @address.send("#{var}=", params[var]) if params[var]
Don't use `send` method here. U can use it only in tests and for debugging. U can use `public_send`

2022-03-22 14:16 UTC, nico-saj commented on app/services/users/settings/address_updater.rb
> +          @address.send("#{var}=", params[var]) if params[var]
but it will be better to permit params and assign_attributes to address

2022-03-22 14:48 UTC, BogdanPerekhrest34 commented
all specs in step6

2022-03-23 11:44 UTC, nico-saj approved these changes

2022-03-23 14:25 UTC, merged