Step2
BogdanPerekhrest34/bookstore pull request #4
Opened 2022-03-07 12:39 UTC by BogdanPerekhrest34

2022-03-14 12:50 UTC, nico-saj requested changes

2022-03-14 12:50 UTC, nico-saj commented on app/models/authors_book.rb
> +  belongs_to :book, dependent: :destroy
`belongs_to` can't have `dependent` option

2022-03-14 12:50 UTC, nico-saj commented on app/services/category_service/generate_categories.rb
> +      generate_categories
Don't create method with only call of another method. Move logic from `generate_categories` here

2022-03-14 12:50 UTC, nico-saj commented on app/services/category_service/generate_categories.rb
> +  class GenerateCategories < ApplicationService
Name classes with nouns: `CategoryGenerator`

2022-03-14 12:50 UTC, nico-saj commented on app/controllers/books_controller.rb
> +class BooksController < ApplicationController
U also need to add authorisation with Pundit or CanCanCan

2022-03-14 12:50 UTC, nico-saj commented on db/migrate/20220217165443_create_books.rb
> +    add_reference :books, :category, index: true, foreign_key: true
`foreign_key: { on_delete: :delete_all }`

All `on_delete` options here have to math `dependent` options in rails models

2022-03-14 12:50 UTC, nico-saj commented on app/views/books/_categories.html.haml
> +      All
Move text to I18n

2022-03-18 11:02 UTC, nico-saj requested changes

2022-03-18 11:02 UTC, nico-saj commented on db/migrate/20220314154821_update_books.rb
> +class UpdateBooks < ActiveRecord::Migration[6.1]
U don't need to create new migrations into single PR. It's ok to rollback several migrations, update, and run ones

2022-03-18 11:02 UTC, nico-saj commented on db/migrate/20220217213055_create_table_authors_books.rb
> +      t.belongs_to :author, index: true
here we also need to add `foreign_key: { on_delete: ...}`

2022-03-18 11:02 UTC, nico-saj commented on app/views/devise/mailer/confirmation_instructions.html.erb
> +<p>Welcome <%= @email %>!</p>
I18n and check other files

2022-03-20 16:04 UTC, BogdanPerekhrest34 commented on app/views/devise/mailer/confirmation_instructions.html.erb
> +<p>Welcome <%= @email %>!</p>
Files which belong to this step I fixed but devise files belongs to another step and in another step I'll fix this

2022-03-22 10:43 UTC, nico-saj requested changes

2022-03-22 10:43 UTC, nico-saj commented on db/migrate/20220318154331_update_authors_books.rb
> +class UpdateAuthorsBooks < ActiveRecord::Migration[6.1]
U mustn't create new migration files within one PR. Just rollback migrations, update files and run updated migrations.

2022-03-22 11:39 UTC, nico-saj requested changes

2022-03-22 11:39 UTC, nico-saj commented on app/controllers/books_controller.rb
> +    if Book.create(book_params)
```
@book.assign_attributes(book_params)
if @book.save
...
```

2022-03-22 11:40 UTC, nico-saj commented on db/migrate/20220218081149_add_columns_to_books.rb
> +# frozen_string_literal: true
The same here. U don't need to update table here. rollback, update, and run migrations

2022-03-22 12:00 UTC, nico-saj approved these changes

2022-03-22 12:07 UTC, merged