migration
BogdanPerekhrest34/bookstore pull request #7
Opened 2022-03-07 13:50 UTC by BogdanPerekhrest34

admin
update book
order
coupon
delivery
addresses

2022-03-24 11:43 UTC, nico-saj requested changes

2022-03-24 11:43 UTC, nico-saj commented on app/forms/checkout_addresses_form.rb
> +    bill = target.addresses.find_or_initialize_by(type: 'Billing')
U have to define constants for `Billing` and `Shipping` in Address model and use them here

2022-03-24 11:43 UTC, nico-saj commented on app/models/order.rb
> +  validates :status, presence: true, acceptance: { accept: %w[in_progress in_queue] }
For status like this u have to use state machine like aasm. It was mentioned in tools

2022-03-24 11:43 UTC, nico-saj commented on app/forms/checkout_addresses_form.rb
> +    billing.valid? && shipping.valid?
Looks like u need `billing.valid? & shipping.valid?`

2022-03-24 11:43 UTC, nico-saj commented on app/forms/checkout_addresses_form.rb
> +    @save = false
remove. It looks weird

2022-03-24 11:43 UTC, nico-saj commented on app/forms/checkout_addresses_form.rb
> +    @save = true
remove

2022-03-24 11:43 UTC, nico-saj commented on app/forms/checkout_addresses_form.rb
> +    return false unless valid?
move to `persist`

2022-03-24 11:43 UTC, nico-saj commented on app/forms/checkout_addresses_form.rb
> +    true
remove

2022-03-24 11:43 UTC, nico-saj commented on app/forms/checkout_addresses_form.rb
> +    bill.assign_attributes(params_for(:billing)) if save?
move `assign_attributes` to `persist`

2022-03-24 11:43 UTC, nico-saj commented on app/forms/checkout_addresses_form.rb
> +    shipping.save
wrap savings in active record transaction

2022-03-24 11:43 UTC, nico-saj commented on app/models/address.rb
> +end
set enum for types

2022-03-24 12:23 UTC, BogdanPerekhrest34 commented on app/models/address.rb
> +end
in next step

2022-03-24 12:25 UTC, BogdanPerekhrest34 commented on app/models/order.rb
> +  validates :status, presence: true, acceptance: { accept: %w[in_progress in_queue] }
using enum in next step

2022-03-24 12:26 UTC, BogdanPerekhrest34 commented on app/forms/checkout_addresses_form.rb
> +    bill = target.addresses.find_or_initialize_by(type: 'Billing')
how do it?

2022-03-24 12:37 UTC, BogdanPerekhrest34 commented on app/forms/checkout_addresses_form.rb
> +    @save = false
what exactly?

2022-03-24 13:45 UTC, nico-saj requested changes

2022-03-24 13:45 UTC, nico-saj commented on app/forms/checkout_addresses_form.rb
> +    @billing = target.addresses.find_or_initialize_by(type: :billing)
`@billing ||= target.addresses.find_or_initialize_by(type: Address.types[:billing])`

2022-03-24 13:45 UTC, nico-saj commented on app/forms/checkout_addresses_form.rb
> +    billing.valid? && shipping.valid?
!

2022-03-24 13:45 UTC, nico-saj commented on app/models/order.rb
> +  validates :status, presence: true, acceptance: { accept: %w[in_progress in_queue] }
No, it's not enough to use enum here. U have to get how to work with state machine

2022-03-24 14:23 UTC, BogdanPerekhrest34 commented on app/forms/checkout_addresses_form.rb
> +    billing.valid? && shipping.valid?
i deleted shipping.valid?
and left billing.valid? && shipping.valid?

2022-03-28 09:02 UTC, nico-saj commented on app/presenters/address_presenter.rb
> +  end
@address = public_send(@type)

2022-03-28 09:03 UTC, nico-saj commented on app/presenters/address_presenter.rb
> +  attr_reader :user, :type
:address

2022-03-28 09:06 UTC, nico-saj commented on app/presenters/address_presenter.rb
> +    user.billing
user.billing || Billing.new

2022-03-28 09:07 UTC, nico-saj commented on app/presenters/address_presenter.rb
> +  def first_name
delegate :first_name, :last_name ..., to: :address

2022-03-28 09:08 UTC, nico-saj commented on app/presenters/book_presenter.rb
> +    if book.description.length > 250
move magic number to Book class constant

2022-03-28 09:09 UTC, nico-saj commented on app/presenters/credit_card_presenter.rb
> +    '**** **** **** ' + credit_card.number.last(4)
move number to constant

2022-03-28 09:10 UTC, nico-saj commented on app/presenters/dropdowns_presenter.rb
> +    newest: 'Newest first',
move text to I18n

2022-03-28 09:13 UTC, nico-saj commented on app/presenters/header_presenter.rb
> +    Order.find_by(id: order_id).order_items.count
`find_by` can return nil. use &. `Order.find_by(id: order_id)&.order_items&.count || 0`

2022-03-28 09:16 UTC, nico-saj commented on app/views/books/_books.html.haml
> +- @books.each do |set_books|
Don't use instance variables in partial views. Pass through local vars

2022-03-28 09:19 UTC, nico-saj commented on app/views/books/_books.html.haml
> +    - presenter = BookPresenter.new(book)
Try to skip definition of vars in view.
Maybe u can create some BooksSetPresenter?. That returns sets of BookPresenters

2022-03-28 11:13 UTC, BogdanPerekhrest34 commented on app/views/books/_books.html.haml
> +    - presenter = BookPresenter.new(book)
didn't realize how to do it

2022-03-28 15:18 UTC, nico-saj requested changes

2022-03-28 15:18 UTC, nico-saj commented on app/views/books/_books.html.haml
> +    - presenter = BookPresenter.new(book)
Remove slice in BooksGenerator
set `@books_set_presenter = BooksSetPresenter.new(@books)` in controller and pass it in views
```
class BooksSetPresenter
  def initialise(books)
    @books = books.map{ |book| BookPresenter.new(book) }
  end

  def set
    @books.each_slice(4).to_a
  end
end
```

2022-03-28 15:18 UTC, nico-saj commented on app/views/books/_dropdown.html.haml
> +- presenter = DropdownsPresenter.new(params[:filter])
can u create presenter in controller?

2022-03-28 15:18 UTC, nico-saj commented on app/views/books/show.html.haml
> +- presenter = BookPresenter.new(@book)
set presenter in controller please

2022-03-28 15:18 UTC, nico-saj commented on db/migrate/20220217165420_create_authors.rb
> +      t.text :description
U can't change migrations in PR. U can change migrations only within one PR.

2022-03-28 15:18 UTC, nico-saj commented on db/migrate/20220228082015_add_reference_to_address.rb
> +    add_reference :addresses, :order, foreign_key: { on_delete: :cascade }, index: true
For example u don't need this migration, because u have new migration with create address. so u have to update old migration, but not create new one

2022-03-28 16:07 UTC, BogdanPerekhrest34 commented on db/migrate/20220228082015_add_reference_to_address.rb
> +    add_reference :addresses, :order, foreign_key: { on_delete: :cascade }, index: true
this migration created because order migration created later than address migration(create_addresses)

2022-03-30 09:03 UTC, nico-saj requested changes

2022-03-30 09:03 UTC, nico-saj commented on app/views/carts/_order_item.html.haml
> +- presenter = BookPresenter.new(item.book)
move to controller and pass through locals

2022-03-30 09:03 UTC, nico-saj commented on app/views/carts/_order_item_xs.html.haml
> +- presenter = BookPresenter.new(item.book)
move to controller and pass through locals

2022-03-30 09:03 UTC, nico-saj commented on app/views/checkout/_list_of_items.html.haml
> +    - presenter = OrderItemPresenter.new(item)
move to controller and pass through locals

2022-03-30 09:03 UTC, nico-saj commented on app/views/home/index.html.haml
> +        - presenter = BookPresenter.new(book)
move to controller

2022-03-30 09:03 UTC, nico-saj commented on app/views/shared/_header.html.haml
> +- presenter = HeaderPresenter.new(session[:order_id])
move to ApplicatoinController method

2022-03-30 09:03 UTC, nico-saj commented on app/views/users/settings/address/_form.html.haml
> +  - presenter = AddressPresenter.new(current_user, type)
move to controller and pass through locals

2022-03-30 10:05 UTC, BogdanPerekhrest34 commented on app/views/users/settings/address/_form.html.haml
> +  - presenter = AddressPresenter.new(current_user, type)
Там не возможно вынести в контроллер, так как презентер зависит от типа адресы а этот тип мы получаем когда вызываем паршел

2022-03-30 10:33 UTC, nico-saj approved these changes

2022-03-30 10:33 UTC, nico-saj commented on app/views/users/settings/address/_form.html.haml
> +  - presenter = AddressPresenter.new(current_user, type)
move to partial call: `render 'form', presenter: AddressPresenter.new(current_user, type)`

2022-03-30 10:56 UTC, merged